### ISSUE TITLE
fail when x and y have different shapes

### ISSUE THREAD

**Issue by 3togo** [aneeshnaik/interp2d#1]
ValueError: operands could not be broadcast together with shapes(7,) (9,)

```
    xp = np.linspace(0, 1, 200)
    yp = np.linspace(-6 * np.pi, 6 * np.pi, 300)

    # gridded data, zp is 2D array
    zp = xp[:, None]**2 * np.sin(yp[None])

    x = np.linspace(0.1, 0.2, 7)
    y = 0.5 * np.pi * np.ones(9)
    out = interp2d(x, y, xp, yp, zp)
    print("out=", out)
```

**Comment by aneeshnaik** [comment]
Hello!

This is expected and desirable behaviour. `x` and `y` here are the coordinates you wish to interpolate at, and so the function is expecting the same shapes for `x` and `y`, i.e. if they both have shape `(N,)`, then the algorithm interpolates `zp` at points (`x[0]`, `y[0]`), (`x[1]`, `y[1]`), ..., (`x[N-1]`, `y[N-1]`). 

I hope that makes sense!
